version: "3"

services:
  workspace:
    build:
      context: ${LOCAL_DOCKER_PATH}/workspace
      args:
        - ARG_CONTAINER_CODE_PATH=${CONTAINER_CODE_PATH}
        - ARG_WORKSPACE_INSTALL_SWOOLE=${WORKSPACE_INSTALL_SWOOLE}
        - ARG_WORKSPACE_INSTALL_MONGODB=${WORKSPACE_INSTALL_MONGODB}
        - ARG_WORKSPACE_INSTALL_REDIS=${WORKSPACE_INSTALL_REDIS}
        - ARG_APP_RUN_PUID=${APP_RUN_PUID}
        - ARG_APP_RUN_PGID=${APP_RUN_PGID}
        - ARG_APP_RUN_NAME=${APP_RUN_NAME}
        - ARG_APP_RUN_GROUP=${APP_RUN_GROUP}
        - ARG_TIMEZONE=${TIMEZONE}
    environment:
      - CONTAINER_CODE_PATH=${CONTAINER_CODE_PATH}
      - CONTAINER_DOCKER_PATH=${CONTAINER_DOCKER_PATH}
      - APP_RUN_PUID=${APP_RUN_PUID}
      - APP_RUN_PGID=${APP_RUN_PGID}
      - APP_RUN_NAME=${APP_RUN_NAME}
      - APP_RUN_GROUP=${APP_RUN_GROUP}
    volumes:
      - ${LOCAL_CODE_PATH}:${CONTAINER_CODE_PATH}
    #覆盖CMD的默认命令，和entrypoint不一样，有单独的entrypoint设置
    #entrypoint 设置后CMD命令将当作参数传入entrypoint
    command: "${CONTAINER_DOCKER_PATH}/workspace/run.sh"
    expose:
      - "28080"
    ports:
      - "${WORKSPACE_SWOOLE_PORT}:28080"
    tty: true
  consul:
    build:
      context: ${LOCAL_DOCKER_PATH}/consul
    network_mode: host
    volumes:
      - ${LOCAL_DOCKER_PATH}/consul/run.sh:/consul/run.sh
      - ${LOCAL_DOCKER_PATH}/consul/config:/consul/config
      - ${LOCAL_CODE_PATH}/storage/consul:/consul/data
    command: /consul/run.sh
  nginx:
    build:
      context: ${LOCAL_DOCKER_PATH}/nginx
      args:
        - ARG_CONTAINER_CODE_PATH=${CONTAINER_CODE_PATH}
        - ARG_APP_RUN_PUID=${APP_RUN_PUID}
        - ARG_APP_RUN_PGID=${APP_RUN_PGID}
        - ARG_APP_RUN_NAME=${APP_RUN_NAME}
        - ARG_APP_RUN_GROUP=${APP_RUN_GROUP}
        - ARG_TIMEZONE=${TIMEZONE}
    environment:
      - CONTAINER_CODE_PATH=${CONTAINER_CODE_PATH}
      - CONTAINER_DOCKER_PATH=${CONTAINER_DOCKER_PATH}
      - APP_RUN_PUID=${APP_RUN_PUID}
      - APP_RUN_PGID=${APP_RUN_PGID}
      - APP_RUN_NAME=${APP_RUN_NAME}
      - APP_RUN_GROUP=${APP_RUN_GROUP}
      - PHP_FPM_PORT=${PHP_FPM_PORT}
    volumes:
      - ${LOCAL_CODE_PATH}:${CONTAINER_CODE_PATH}
    command: ${CONTAINER_DOCKER_PATH}/nginx/run.sh
    expose:
      - "80"
      - "443"
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_SSL_PORT}:443"
    links:
      - php-fpm:php-fpm
    depends_on:
      - php-fpm
      - workspace
  php-fpm:
    build:
      context: ${LOCAL_DOCKER_PATH}/php-fpm
      args:
        - ARG_CONTAINER_CODE_PATH=${CONTAINER_CODE_PATH}
        - ARG_PHP_FPM_INSTALL_MONGODB=${PHP_FPM_INSTALL_MONGODB}
        - ARG_PHP_FPM_INSTALL_REDIS=${PHP_FPM_INSTALL_REDIS}
        - ARG_TIMEZONE=${TIMEZONE}
    environment:
      - CONTAINER_CODE_PATH=${CONTAINER_CODE_PATH}
      - CONTAINER_DOCKER_PATH=${CONTAINER_DOCKER_PATH}
      - APP_RUN_PUID=${APP_RUN_PUID}
      - APP_RUN_PGID=${APP_RUN_PGID}
      - APP_RUN_NAME=${APP_RUN_NAME}
      - APP_RUN_GROUP=${APP_RUN_GROUP}
    command: ${CONTAINER_DOCKER_PATH}/php-fpm/run.sh
    volumes:
      - ${LOCAL_CODE_PATH}:${CONTAINER_CODE_PATH}
    expose:
      - "9000"
    ports:
      - "${PHP_FPM_PORT}:9000"